[package]
name = "bc-shamir"
version = "0.3.3"
edition = "2021"
description = "Shamir's Secret Sharing (SSS) for Rust."
authors = ["Blockchain Commons"]
keywords = ["cryptography"]
repository = "https://github.com/BlockchainCommons/bc-shamir-rust"
readme = "README.md"
license = "BSD-2-Clause-Patent"
categories = ["cryptography"]
documentation = "https://docs.rs/bc-shamir"

[dependencies]
bc-rand = "^0.1.2"

# bc-crypto = { path = "../bc-crypto-rust" }
bc-crypto = "^0.3.0"

thiserror = "^1.0.48"

[dev-dependencies]
hex-literal = "^0.4.1"
hex = "^0.4.3"
version-sync = "^0.9.0"
